%% SPDX-FileCopyrightText: 2026 Pablo Gallardo
%% SPDX-License-Identifier: CC-BY-4.0

graph LR
   31110018[Modelado estadístico de datos] --> 31110037[Aprendizaje automático 1]
   31110018 --> 31110094[Modelos bayesianos jerárquicos]
   31110022[Programación en Entornos de Datos] --> 31110041[Minería de textos]
   31110022 --> 31110037
   31110022 --> 31110060[Visualización de datos]
   31110037 --> 31110130[Aprendizaje Automático 2]
   31110037 --> 31110111[Deep Learning]
   31110056[Infraestructuras computacionales para procesamiento de datos masivos] --> 31110111
   31110041 --> 31110107[Minería de datos de los medios sociales]